language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pytest pytest-cov codecov
script:
  - py.test --cov=pip_validate
after_success:
  - codecov
